--
-- THE LAB operations (declarative source; see migration 20261009120000).
-- Shopify orders and checkouts, Cal.com appointments, deal lead source and
-- stage history, integration event log, and follow-up automation rules.
--

--
-- Deals: where the lead came from, and when it last changed stage
--
-- Columns added to public.deals:
--   lead_source text
--   stage_changed_at timestamp with time zone not null default now()

create table public.deal_stage_history (
    id bigint generated by default as identity primary key,
    deal_id bigint not null references public.deals(id) on delete cascade,
    from_stage text,
    to_stage text not null,
    changed_at timestamp with time zone not null default now()
);
create index deal_stage_history_deal_id_idx on public.deal_stage_history (deal_id);
create index deal_stage_history_changed_at_idx on public.deal_stage_history (changed_at);

create or replace function public.track_deal_stage()
 returns trigger
 language plpgsql
 security definer
 set search_path to ''
as $function$
begin
  if tg_op = 'INSERT' then
    new.stage_changed_at := coalesce(new.stage_changed_at, now());
    return new;
  end if;
  if new.stage is distinct from old.stage then
    new.stage_changed_at := now();
  end if;
  return new;
end;
$function$;

create or replace function public.log_deal_stage()
 returns trigger
 language plpgsql
 security definer
 set search_path to ''
as $function$
begin
  if tg_op = 'INSERT' then
    insert into public.deal_stage_history (deal_id, from_stage, to_stage, changed_at)
    values (new.id, null, new.stage, new.created_at);
  elsif new.stage is distinct from old.stage then
    insert into public.deal_stage_history (deal_id, from_stage, to_stage)
    values (new.id, old.stage, new.stage);
  end if;
  return null;
end;
$function$;

create trigger deals_track_stage before insert or update of stage on public.deals
    for each row execute function public.track_deal_stage();
create trigger deals_log_stage after insert or update of stage on public.deals
    for each row execute function public.log_deal_stage();

--
-- Shopify orders
--
create table public.orders (
    id bigint generated by default as identity primary key,
    shopify_order_id text unique,
    order_number text not null,
    contact_id bigint references public.contacts(id) on delete set null,
    deal_id bigint references public.deals(id) on delete set null,
    source text,
    financial_status text,
    fulfillment_status text,
    currency text not null default 'CAD',
    subtotal numeric(12, 2),
    total numeric(12, 2) not null default 0,
    refunded_amount numeric(12, 2) not null default 0,
    line_items jsonb not null default '[]'::jsonb,
    categories text[] not null default '{}',
    is_deposit boolean not null default false,
    ordered_at timestamp with time zone not null default now(),
    cancelled_at timestamp with time zone,
    created_at timestamp with time zone not null default now(),
    sales_id bigint references public.sales(id),
    constraint orders_line_items_is_array check (jsonb_typeof(line_items) = 'array')
);
create index orders_contact_id_idx on public.orders (contact_id);
create index orders_ordered_at_idx on public.orders (ordered_at);

--
-- Shopify checkouts (for abandoned cart follow-up)
--
create table public.shopify_checkouts (
    id bigint generated by default as identity primary key,
    checkout_token text not null unique,
    contact_id bigint references public.contacts(id) on delete set null,
    email text,
    phone text,
    customer_name text,
    total numeric(12, 2) not null default 0,
    line_items jsonb not null default '[]'::jsonb,
    recovery_url text,
    completed_at timestamp with time zone,
    task_id bigint references public.tasks(id) on delete set null,
    checkout_updated_at timestamp with time zone not null default now(),
    created_at timestamp with time zone not null default now()
);
create index shopify_checkouts_open_idx on public.shopify_checkouts (checkout_updated_at) where completed_at is null;

--
-- Appointments (from Cal.com, or added by hand)
--
create table public.appointments (
    id bigint generated by default as identity primary key,
    external_id text unique,
    source text not null default 'manual',
    contact_id bigint references public.contacts(id) on delete set null,
    deal_id bigint references public.deals(id) on delete set null,
    task_id bigint references public.tasks(id) on delete set null,
    title text not null,
    resource text not null default 'eric',
    start_at timestamp with time zone not null,
    end_at timestamp with time zone not null,
    status text not null default 'booked',
    deposit_paid boolean not null default false,
    vehicle text,
    notes text,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    sales_id bigint references public.sales(id),
    constraint appointments_resource_check check (resource in ('detailing-bay', 'eric')),
    constraint appointments_status_check check (status in ('booked', 'rescheduled', 'cancelled', 'completed', 'no_show')),
    constraint appointments_time_check check (end_at > start_at)
);
create index appointments_start_at_idx on public.appointments (start_at);
create index appointments_contact_id_idx on public.appointments (contact_id);

--
-- Integration event log (idempotency and troubleshooting; written by edge functions only)
--
create table public.integration_events (
    id bigint generated by default as identity primary key,
    source text not null,
    event_type text not null,
    external_id text,
    status text not null default 'received',
    error text,
    client_hash text,
    payload jsonb,
    created_at timestamp with time zone not null default now()
);
create unique index integration_events_dedupe_idx on public.integration_events (source, external_id) where external_id is not null;
create index integration_events_rate_idx on public.integration_events (source, client_hash, created_at);

--
-- Automation log (makes the follow-up rules run once per deal per rule)
--
create table public.automation_log (
    id bigint generated by default as identity primary key,
    rule text not null,
    subject_id bigint not null,
    task_id bigint references public.tasks(id) on delete set null,
    created_at timestamp with time zone not null default now(),
    constraint automation_log_unique unique (rule, subject_id)
);

--
-- sales_id defaults (same pattern as the other tables)
--
create trigger set_orders_sales_id_trigger before insert on public.orders
    for each row execute function public.set_sales_id_default();
create trigger set_appointments_sales_id_trigger before insert on public.appointments
    for each row execute function public.set_sales_id_default();

create or replace function public.touch_updated_at()
 returns trigger
 language plpgsql
 set search_path to ''
as $function$
begin
  new.updated_at := now();
  return new;
end;
$function$;
create trigger appointments_touch_updated_at before update on public.appointments
    for each row execute function public.touch_updated_at();

--
-- Row level security
--
alter table public.deal_stage_history enable row level security;
alter table public.orders enable row level security;
alter table public.shopify_checkouts enable row level security;
alter table public.appointments enable row level security;
alter table public.integration_events enable row level security;
alter table public.automation_log enable row level security;

-- Stage history is written by triggers only
create policy "Enable read access for authenticated users" on public.deal_stage_history for select to authenticated using (true);

-- Orders: staff can read, and import/edit them (the JSON import runs as the signed-in user)
create policy "Enable read access for authenticated users" on public.orders for select to authenticated using (true);
create policy "Enable insert for authenticated users only" on public.orders for insert to authenticated with check (true);
create policy "Enable update for authenticated users only" on public.orders for update to authenticated using (true) with check (true);
create policy "Orders Delete Policy" on public.orders for delete to authenticated using (true);

-- Checkouts come from Shopify only
create policy "Enable read access for authenticated users" on public.shopify_checkouts for select to authenticated using (true);

-- Appointments: staff manage them (Cal.com ones are written by the webhook)
create policy "Enable read access for authenticated users" on public.appointments for select to authenticated using (true);
create policy "Enable insert for authenticated users only" on public.appointments for insert to authenticated with check (true);
create policy "Enable update for authenticated users only" on public.appointments for update to authenticated using (true) with check (true);
create policy "Appointments Delete Policy" on public.appointments for delete to authenticated using (true);

create policy "Enable read access for authenticated users" on public.integration_events for select to authenticated using (true);
create policy "Enable read access for authenticated users" on public.automation_log for select to authenticated using (true);

grant select on table public.deal_stage_history to authenticated;
grant all on table public.deal_stage_history to service_role;
grant select, insert, update, delete on table public.orders to authenticated;
grant all on table public.orders to service_role;
grant select on table public.shopify_checkouts to authenticated;
grant all on table public.shopify_checkouts to service_role;
grant select, insert, update, delete on table public.appointments to authenticated;
grant all on table public.appointments to service_role;
grant select on table public.integration_events to authenticated;
grant all on table public.integration_events to service_role;
grant select on table public.automation_log to authenticated;
grant all on table public.automation_log to service_role;
grant usage, select on all sequences in schema public to authenticated, service_role;

--
-- Follow-up rules. Idempotent: each rule fires once per subject (automation_log).
-- Runs every 15 minutes when pg_cron is available, and whenever the dashboard loads.
--
create or replace function public.lab_default_sales_id()
 returns bigint
 language sql
 stable
 security definer
 set search_path to ''
as $function$
  select id from public.sales
  where not disabled
  order by (lower(email) = 'info@luxxautomotiveboutique.com') desc, administrator desc, id
  limit 1
$function$;

create or replace function public.lab_add_task(p_rule text, p_subject_id bigint, p_contact_id bigint, p_type text, p_text text, p_sales_id bigint)
 returns bigint
 language plpgsql
 security definer
 set search_path to ''
as $function$
declare
  v_task_id bigint;
begin
  if p_contact_id is null then
    return null;
  end if;
  insert into public.automation_log (rule, subject_id) values (p_rule, p_subject_id)
  on conflict (rule, subject_id) do nothing;
  if not found then
    return null;
  end if;
  insert into public.tasks (contact_id, type, text, due_date, sales_id)
  values (p_contact_id, p_type, p_text, now(), coalesce(p_sales_id, public.lab_default_sales_id()))
  returning id into v_task_id;
  update public.automation_log set task_id = v_task_id where rule = p_rule and subject_id = p_subject_id;
  return v_task_id;
end;
$function$;

create or replace function public.run_automations()
 returns integer
 language plpgsql
 security definer
 set search_path to ''
as $function$
declare
  r record;
  v_count integer := 0;
begin
  -- 1. Quote sent 3+ days ago with no movement: first follow-up
  for r in
    select d.id, d.name, d.contact_ids[1] as contact_id, d.sales_id
    from public.deals d
    where d.stage = 'quoted' and d.archived_at is null
      and d.stage_changed_at < now() - interval '3 days'
  loop
    if public.lab_add_task('quote-follow-up-1', r.id, r.contact_id, 'follow-up',
        'Follow up on quote: ' || r.name, r.sales_id) is not null then
      v_count := v_count + 1;
    end if;
  end loop;

  -- 2. Still no movement 7+ days after the quote: second follow-up
  for r in
    select d.id, d.name, d.contact_ids[1] as contact_id, d.sales_id
    from public.deals d
    where d.stage = 'quoted' and d.archived_at is null
      and d.stage_changed_at < now() - interval '7 days'
      and exists (select 1 from public.automation_log a where a.rule = 'quote-follow-up-1' and a.subject_id = d.id)
  loop
    if public.lab_add_task('quote-follow-up-2', r.id, r.contact_id, 'follow-up',
        'Second follow-up on quote: ' || r.name, r.sales_id) is not null then
      v_count := v_count + 1;
    end if;
  end loop;

  -- 3. Quiet 10+ days after the quote and two follow-ups: suggest Not now
  for r in
    select d.id, d.name, d.contact_ids[1] as contact_id, d.sales_id
    from public.deals d
    where d.stage = 'quoted' and d.archived_at is null
      and d.stage_changed_at < now() - interval '10 days'
      and exists (select 1 from public.automation_log a where a.rule = 'quote-follow-up-2' and a.subject_id = d.id)
  loop
    if public.lab_add_task('quote-not-now', r.id, r.contact_id, 'follow-up',
        'No reply after two follow-ups. Move to Not now? ' || r.name, r.sales_id) is not null then
      v_count := v_count + 1;
    end if;
  end loop;

  -- 4. Booked 2+ days ago and the deposit is still unpaid
  for r in
    select d.id, d.name, d.contact_ids[1] as contact_id, d.sales_id
    from public.deals d
    where d.stage = 'booked' and d.archived_at is null
      and d.stage_changed_at < now() - interval '2 days'
  loop
    if public.lab_add_task('deposit-reminder', r.id, r.contact_id, 'deposit',
        'Deposit not paid yet: ' || r.name, r.sales_id) is not null then
      v_count := v_count + 1;
    end if;
  end loop;

  -- 5. Website booking request, but no booking after a day
  for r in
    select d.id, d.name, d.contact_ids[1] as contact_id, d.sales_id
    from public.deals d
    where d.stage = 'qualified' and d.archived_at is null and d.lead_source = 'website'
      and d.stage_changed_at < now() - interval '1 day'
      and not exists (select 1 from public.appointments a where a.deal_id = d.id)
  loop
    if public.lab_add_task('booking-not-finished', r.id, r.contact_id, 'call',
        'Started booking online but did not pick a time: ' || r.name, r.sales_id) is not null then
      v_count := v_count + 1;
    end if;
  end loop;

  -- 6. Checkout over $2,000 left unpaid for an hour: Eric calls
  for r in
    select c.id, c.contact_id, c.total, c.customer_name
    from public.shopify_checkouts c
    where c.completed_at is null and c.task_id is null and c.total >= 2000
      and c.checkout_updated_at < now() - interval '1 hour'
      and c.checkout_updated_at > now() - interval '14 days'
  loop
    if public.lab_add_task('abandoned-cart', r.id, r.contact_id, 'call',
        'Abandoned cart $' || to_char(r.total, 'FM999,999,990.00') || '. Call about the order.', null) is not null then
      update public.shopify_checkouts set task_id =
        (select a.task_id from public.automation_log a where a.rule = 'abandoned-cart' and a.subject_id = r.id)
      where id = r.id;
      v_count := v_count + 1;
    end if;
  end loop;

  return v_count;
end;
$function$;

revoke all on function public.run_automations() from public, anon;
grant execute on function public.run_automations() to authenticated, service_role;
revoke all on function public.lab_add_task(text, bigint, bigint, text, text, bigint) from public, anon, authenticated;
grant execute on function public.lab_add_task(text, bigint, bigint, text, text, bigint) to service_role;
revoke all on function public.lab_default_sales_id() from public, anon;
grant execute on function public.lab_default_sales_id() to authenticated, service_role;

-- Scheduling (pg_cron job 'the-lab-automations', every 15 minutes) lives in the migration.
