--
-- Vehicles (declarative source; see migration 20261009210000).
-- Many per customer or business; jobs and appointments can point at one.
--

create table public.vehicles (
    id bigint generated by default as identity primary key,
    contact_id bigint references public.contacts(id) on delete cascade,
    company_id bigint references public.companies(id) on delete set null,
    year smallint,
    make text,
    model text,
    trim text,
    platform text,
    engine text,
    transmission text,
    size_class text,
    vin text,
    plate text,
    colour text,
    mods text,
    notes text,
    is_primary boolean not null default false,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    sales_id bigint references public.sales(id),
    constraint vehicles_year_check check (year is null or year between 1900 and 2100),
    constraint vehicles_vin_check check (vin is null or char_length(vin) <= 17),
    constraint vehicles_owner_check check (contact_id is not null or company_id is not null),
    constraint vehicles_platform_check check (platform is null or platform in
        ('cummins', 'duramax', 'powerstroke', 'half-ton', 'kenworth', 'gas', 'sxs', 'other')),
    constraint vehicles_size_class_check check (size_class is null or size_class in
        ('car', 'suv-5-6', 'suv-7-8', 'truck', 'sxs', 'commercial'))
);
create index vehicles_contact_id_idx on public.vehicles (contact_id);
create index vehicles_company_id_idx on public.vehicles (company_id);
create index vehicles_vin_idx on public.vehicles (upper(vin)) where vin is not null;

create trigger set_vehicles_sales_id_trigger before insert on public.vehicles
    for each row execute function public.set_sales_id_default();
create trigger vehicles_touch_updated_at before update on public.vehicles
    for each row execute function public.touch_updated_at();

alter table public.vehicles enable row level security;
create policy "Enable read access for authenticated users" on public.vehicles for select to authenticated using (true);
create policy "Enable insert for authenticated users only" on public.vehicles for insert to authenticated with check (true);
create policy "Enable update for authenticated users only" on public.vehicles for update to authenticated using (true) with check (true);
create policy "Vehicles Delete Policy" on public.vehicles for delete to authenticated using (true);
grant select, insert, update, delete on table public.vehicles to authenticated;
grant all on table public.vehicles to service_role;
grant usage, select on sequence public.vehicles_id_seq to authenticated, service_role;

alter table public.deals
    add constraint deals_vehicle_id_fkey foreign key (vehicle_id) references public.vehicles(id) on delete set null;
alter table public.appointments
    add constraint appointments_vehicle_id_fkey foreign key (vehicle_id) references public.vehicles(id) on delete set null;
create index deals_vehicle_id_idx on public.deals (vehicle_id);
