--
-- Packages (declarative source; see migration 20261009230000).
-- The service catalog copied from Shopify; Shopify owns names and prices.
--

create table public.packages (
    id bigint generated by default as identity primary key,
    shopify_product_id text not null unique,
    title text not null,
    shopify_title text not null,
    vendor text,
    category text,
    bay text,
    price numeric(12, 2),
    price_max numeric(12, 2),
    variants jsonb not null default '[]'::jsonb,
    status text not null default 'active',
    shopify_updated_at timestamp with time zone,
    synced_at timestamp with time zone not null default now(),
    -- "package": a shop service or Gridiron bumper (goes on jobs);
    -- "product": diesel parts, accessories, merch and the deposit
    kind text not null default 'package',
    product_type text,
    handle text,
    image_url text,
    -- units in stock across variants; null when Shopify does not track stock
    inventory integer,
    constraint packages_variants_is_array check (jsonb_typeof(variants) = 'array'),
    constraint packages_bay_check check (bay is null or bay in ('boutique', 'parts')),
    constraint packages_status_check check (status in ('active', 'unlisted', 'draft', 'archived', 'deleted')),
    constraint packages_kind_check check (kind in ('package', 'product'))
);
create index packages_category_idx on public.packages (category);
create index packages_kind_idx on public.packages (kind);

alter table public.packages enable row level security;
create policy "Enable read access for authenticated users" on public.packages for select to authenticated using (true);
grant select on table public.packages to authenticated;
grant all on table public.packages to service_role;

-- One row per order line, so the CRM can find who bought a package or part
-- (line names carry the variant: "Prerunner Front Bumper - Black").
create or replace view public.order_lines with (security_invoker = on) as
select
    o.id || '-' || l.ordinality as id,
    o.id as order_id,
    o.order_number,
    o.contact_id,
    o.ordered_at,
    o.cancelled_at,
    l.item->>'name' as name,
    coalesce((l.item->>'quantity')::numeric, 1) as quantity,
    coalesce((l.item->>'price')::numeric, 0) as price
from public.orders o
cross join lateral jsonb_array_elements(o.line_items) with ordinality as l(item, ordinality);

grant select on table public.order_lines to authenticated;
grant select on table public.order_lines to service_role;
