-- THE LAB customer profiles: vehicles (many per customer or fleet), how each
-- customer wants to be reached, SMS consent, where they came from and their
-- detailing membership. Jobs and appointments can point at a vehicle.
-- Mirrors supabase/schemas/09_vehicles.sql.

--
-- Customer profile fields
--
alter table public.contacts add column if not exists preferred_contact text;
alter table public.contacts add column if not exists sms_consent boolean not null default false;
alter table public.contacts add column if not exists sms_consent_at timestamp with time zone;
alter table public.contacts add column if not exists lead_source text;
alter table public.contacts add column if not exists membership text;
alter table public.contacts add column if not exists membership_since date;
alter table public.contacts add column if not exists city text;
alter table public.contacts add column if not exists province text;

alter table public.contacts add constraint contacts_preferred_contact_check
    check (preferred_contact is null or preferred_contact in ('text', 'call', 'email'));
alter table public.contacts add constraint contacts_membership_check
    check (membership is null or membership in ('monthly-signature', 'lab-syndicate'));

--
-- Vehicles
--
create table public.vehicles (
    id bigint generated by default as identity primary key,
    contact_id bigint references public.contacts(id) on delete cascade,
    company_id bigint references public.companies(id) on delete set null,
    year smallint,
    make text,
    model text,
    trim text,
    platform text,
    engine text,
    transmission text,
    size_class text,
    vin text,
    plate text,
    colour text,
    mods text,
    notes text,
    is_primary boolean not null default false,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    sales_id bigint references public.sales(id),
    constraint vehicles_year_check check (year is null or year between 1900 and 2100),
    constraint vehicles_vin_check check (vin is null or char_length(vin) <= 17),
    constraint vehicles_owner_check check (contact_id is not null or company_id is not null),
    constraint vehicles_platform_check check (platform is null or platform in
        ('cummins', 'duramax', 'powerstroke', 'half-ton', 'kenworth', 'gas', 'sxs', 'other')),
    constraint vehicles_size_class_check check (size_class is null or size_class in
        ('car', 'suv-5-6', 'suv-7-8', 'truck', 'sxs', 'commercial'))
);
create index vehicles_contact_id_idx on public.vehicles (contact_id);
create index vehicles_company_id_idx on public.vehicles (company_id);
create index vehicles_vin_idx on public.vehicles (upper(vin)) where vin is not null;

create trigger set_vehicles_sales_id_trigger before insert on public.vehicles
    for each row execute function public.set_sales_id_default();
create trigger vehicles_touch_updated_at before update on public.vehicles
    for each row execute function public.touch_updated_at();

alter table public.vehicles enable row level security;
create policy "Enable read access for authenticated users" on public.vehicles for select to authenticated using (true);
create policy "Enable insert for authenticated users only" on public.vehicles for insert to authenticated with check (true);
create policy "Enable update for authenticated users only" on public.vehicles for update to authenticated using (true) with check (true);
create policy "Vehicles Delete Policy" on public.vehicles for delete to authenticated using (true);
grant select, insert, update, delete on table public.vehicles to authenticated;
grant all on table public.vehicles to service_role;
grant usage, select on sequence public.vehicles_id_seq to authenticated, service_role;

--
-- Jobs and appointments can name the vehicle
--
alter table public.deals add column if not exists vehicle_id bigint references public.vehicles(id) on delete set null;
alter table public.appointments add column if not exists vehicle_id bigint references public.vehicles(id) on delete set null;
create index if not exists deals_vehicle_id_idx on public.deals (vehicle_id);

--
-- Customer list view: new profile fields, plus vehicles for search
--
drop view if exists public.contacts_summary;
create view public.contacts_summary with (security_invoker = on) as
select
    co.id,
    co.first_name,
    co.last_name,
    co.gender,
    co.title,
    co.background,
    co.avatar,
    co.first_seen,
    co.last_seen,
    co.has_newsletter,
    co.status,
    co.tags,
    co.company_id,
    co.sales_id,
    co.linkedin_url,
    co.email_jsonb,
    co.phone_jsonb,
    co.preferred_contact,
    co.sms_consent,
    co.sms_consent_at,
    co.lead_source,
    co.membership,
    co.membership_since,
    co.city,
    co.province,
    (jsonb_path_query_array(co.email_jsonb, '$[*]."email"'))::text as email_fts,
    (jsonb_path_query_array(co.phone_jsonb, '$[*]."number"'))::text as phone_fts,
    c.name as company_name,
    count(distinct t.id) filter (where t.done_date is null) as nb_tasks,
    (
        select string_agg(concat_ws(' ', v.year, v.make, v.model, v.trim, v.engine, v.vin, v.plate), ' | ')
        from public.vehicles v where v.contact_id = co.id
    ) as vehicles_fts,
    (
        select concat_ws(' ', v.year, v.make, v.model)
        from public.vehicles v where v.contact_id = co.id
        order by v.is_primary desc, v.id
        limit 1
    ) as vehicle_label
from public.contacts co
    left join public.tasks t on co.id = t.contact_id
    left join public.companies c on co.company_id = c.id
group by co.id, c.name;

-- Same grants as before the view was rebuilt (rows still follow the tables' RLS)
grant all on table public.contacts_summary to anon;
grant all on table public.contacts_summary to authenticated;
grant all on table public.contacts_summary to service_role;
